//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DR.Marvin.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class attachment
    {
        public int id { get; set; }
        public int essence_Id { get; set; }
        public string path { get; set; }
        public int attachmentType { get; set; }
        public string arguments { get; set; }
    }
}
