//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DR.Marvin.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class command
    {
        public string urn { get; set; }
        public int type { get; set; }
        public string username { get; set; }
    }
}
