//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DR.Marvin.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class essence
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public essence()
        {
            this.attachment = new HashSet<attachment>();
            this.essenceFile = new HashSet<essenceFile>();
        }
    
        public int id { get; set; }
        public string path { get; set; }
        public int stateFormat { get; set; }
        public int stateFlag { get; set; }
        public int duration { get; set; }
        public int aspectratio { get; set; }
        public string customFormat { get; set; }
        public int resolution { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<attachment> attachment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<essenceFile> essenceFile { get; set; }
    }
}
