//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DR.Marvin.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class execution_essence
    {
        public int essence_Id { get; set; }
        public System.Guid executiontask_Id { get; set; }
        public int executionEssenceType { get; set; }
    
        public virtual essence essence { get; set; }
    }
}
