//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DR.Marvin.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class executiontask
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public executiontask()
        {
            this.execution_essence = new HashSet<execution_essence>();
        }
    
        public System.Guid Id { get; set; }
        public string urn { get; set; }
        public Nullable<System.DateTime> startTime { get; set; }
        public Nullable<System.DateTime> endTime { get; set; }
        public long estimation { get; set; }
        public int executionState { get; set; }
        public string pluginUrn { get; set; }
        public System.Guid executionPlan_Id { get; set; }
        public string foreignKey { get; set; }
        public int sortOrder { get; set; }
        public string arguments { get; set; }
        public int numberOfRetries { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<execution_essence> execution_essence { get; set; }
    }
}
