//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DR.Marvin.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class executionPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public executionPlan()
        {
            this.executiontask = new HashSet<executiontask>();
        }
    
        public string urn { get; set; }
        public int executionState { get; set; }
        public Nullable<int> currentEssence_Id { get; set; }
        public System.Guid jobId { get; set; }
        public Nullable<int> activeTaskIndex { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<executiontask> executiontask { get; set; }
    }
}
