//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DR.Marvin.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public job()
        {
            this.job_essence = new HashSet<job_essence>();
        }
    
        public System.Guid id { get; set; }
        public string urn { get; set; }
        public System.DateTime issued { get; set; }
        public System.DateTime dueDate { get; set; }
        public int priority { get; set; }
        public Nullable<System.DateTime> endTime { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime modified { get; set; }
        public string callbackUrl { get; set; }
        public string name { get; set; }
        public string sourceUrn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<job_essence> job_essence { get; set; }
        public virtual executionPlan executionPlan { get; set; }
    }
}
