//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DR.Marvin.Repositories
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MarvinEntities : DbContext
    {
        public MarvinEntities()
            : base("name=MarvinEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<attachment> attachment { get; set; }
        public virtual DbSet<essence> essence { get; set; }
        public virtual DbSet<executiontask> executiontask { get; set; }
        public virtual DbSet<job> job { get; set; }
        public virtual DbSet<execution_essence> execution_essence { get; set; }
        public virtual DbSet<job_essence> job_essence { get; set; }
        public virtual DbSet<executionPlan> executionPlan { get; set; }
        public virtual DbSet<semaphore> semaphore { get; set; }
        public virtual DbSet<essenceFile> essenceFile { get; set; }
        public virtual DbSet<command> command { get; set; }
        public virtual DbSet<healthCounter> healthCounter { get; set; }
    }
}
