//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DR.Marvin.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class semaphore
    {
        public string semaphoreId { get; set; }
        public string currentOwnerId { get; set; }
        public System.DateTime heartBeat { get; set; }
        public byte[] rowversion { get; set; }
    }
}
